name: 'Build, Package and Dist image'

on:
  workflow_dispatch:
    inputs:
      repoTag:
        description: 'Repo of submit'
        required: true
jobs:
  build:
    name: 'Build version ${{ github.event.inputs.vvr_version }}'
    runs-on: ubuntu-22.04
    environment: AWS Env
    permissions: # required for using the Github OIDC Provider with AWS IAM
      id-token: write
      contents: read

    steps:
      - name: Checkout connector-packager
        uses: actions/checkout@v3
        with:
          path: connector-packager

      - name: Set up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.2.5

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $ECR_REPO
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          ECR_REPO: '423583746720.dkr.ecr.eu-central-1.amazonaws.com/test-ecr'
          VERSION: ${{ github.event.inputs.repoTag }}

      - name: Maven Build Connectors
        working-directory: spiVersionLogger
        run: |
          chmod 755 build-and-deploy.sh
          ./build-and-deploy.sh $ECR_REPO:$VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          ECR_REPO: '423583746720.dkr.ecr.eu-central-1.amazonaws.com/test-ecr'
          VERSION: ${{ github.event.inputs.repoTag }}

